
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://ferquinz.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /ferquinz.github.io

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Fernando Sanchiz"
title: "{ Fernando Sanchiz }"
description: "Blog and website of Fernando Sanchiz, blogging mainly for tech. Opinions expressed are mine."
keywords: "sanchiz, fernando, personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "/img/puente.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The Object Was Not To Stay Alive But To Stay Human."
  - text: "A person who never made a mistake never tried anything new."

me-img: "/img/author.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "ferquinz"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/momit.jpg"
    date: "April 2016 - Today"
    description: "Java Developer at Momit"
  - image: "/img/timeline/mercanza.gif"
    date: "September 2014 - April 2016"
    description: ".Net Developer at Mercanza for different clients."

# First image of the Timeline

timeline-img: "/img/author.jpg"

###########
# Contact #
###########

email: "ferquinz10@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Fernando Sanchiz is an awesome person. He lives in Spain. In his spare time, Fernando likes to do sport and work on his own projects."
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/ferquinz"
  - title: "linkedin"
    url: "https://es.linkedin.com/in/fernando-sanchiz-42b79ba4"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Portfolio: 'portfolio'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
